### ISSUE TITLE
Include SPDX short identifiers copyright block comments

### ISSUE THREAD

**Issue by davidpolverari** [resurrecting-open-source-projects/packit#18]
According to https://spdx.org/, **SPDX** (Software Packet Data Exchange) is 

> "an open standard for communicating software bill of materials (including components, licenses, copyrights, and security references)."

SPDX short identifiers provide a unobtrusive, machine-readable and language-independent way to convey license information. It makes header files smaller and allows organizations and other interested third-parties (eg.: Linux distribution developers) to automatically parse license information of all source files in a project.

What follows is an example of a tentative copyright block comment using SPDX short identifiers:

```
/*
 * Packit -- network injection and capture tool
 *
 * Original author: Darren Bounds <dbounds@intrusense.com>
 *
 * Copyright 2002-2004 Darren Bounds <dbounds@intrusense.com>
 * Copyright 2004-2005 Dennis Vshivkov <walrus@amur.ru>
 * Copyright 2006      Deniz Adrian <adrian@netzquadrat.de>
 * Copyright 2013      Mats Erik Andersson <gnu@gisladisker.se>
 * Copyright 2017      Robert Krause <ruport@f00l.de>
 * Copyright 2017      Sharad B
 * Copyright 2020      David Polverari <david.polverari@gmail.com>
 * Copyright 2020      Jeroen Roovers <jer@gentoo.org>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * See LICENSE file for more information.
 *
 * packit official page at https://github.com/resurrecting-open-source-projects/packit
 */
```

It could be reduced even further, by adopting other strategies, like moving the name of the authors/contributors to other files and referencing them on the header:

```
/*
 * Packit -- network injection and capture tool
 *
 * Original author: Darren Bounds <dbounds@intrusense.com>
 *
 * Copyright 2002-2020 Darren Bounds <dbounds@intrusense.com> and Contributors.
 * See CONTRIBUTORS file for details.
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 * See LICENSE file for more information.
 *
 * packit official page at https://github.com/resurrecting-open-source-projects/packit
 */
```
Even if we can't remove the standard GPL header, I think the addition of SPDX short identifiers still benefits a lot of third-parties. Thus I propose a discussion to check whether and how we could use those SPDX short identifiers on the project.

**Comment by davidpolverari** [comment]
See also: https://reuse.software/spec/

**Comment by eribertomota** [comment]
Em sex., 13 de mar. de 2020 às 01:32, davidpolverari <
notifications@github.com> escreveu:

> See also: https://reuse.software/spec/
>
>
>
Hi David,

IMHO, all contributors should be added in each file using copyright string.
It is a way to register the contributions and its related rights. For me,
in FOSS, it is like a recognition for the work that has been done.

Cheers,

Eriberto

**Comment by davidpolverari** [comment]
Hi! I agree that all contributions should be credited. But as projects grows, with copyright notices for every contribution, the file headers become unwieldy. Anyways, that was only an additional suggestion on this issue, and it is something we can keep that way or, if deemed worth, we can open another issue to discuss.

Apart from that, I think at least we should adopt the usage of the SPDX short identifier in all headers. It doesn't mandate the exclusion of anything, but benefits distribution packagers and organizations, by providing a machine-readable way to verify license compliance. There are some variations, as the one presented on the original issue text, and other projects add yet another single line comment on the top of the file containing the identifier. I, for one, prefer embedding the SPDX identifier on the existing headers.

What do you think about it?

**Comment by eribertomota** [comment]
The project uses GPL-2+. Current headers follow the GPL instructions:

"To do so, attach the following notices to the program. It is safest to
attach them to the start of each source file to most effectively convey the
exclusion of warranty; and each file should have at least the "copyright"
line and a pointer to where the full notice is found."

However, I and Debian don't see problems using the purposed mode from you.

Thanks!

Eriberto

**Comment by davidpolverari** [comment]
After reading https://spdx.org/ids-how and other considerations made on several other sources, I think the safest way to include them is by just adding them to the standard copyright block comment on each source file, without removing any other line:

```
/*
 * Packit -- network injection and capture tool
 *
 * Original author: Darren Bounds <dbounds@intrusense.com>
 *
 * Copyright 2002-2004 Darren Bounds <dbounds@intrusense.com>
 * Copyright 2004-2005 Dennis Vshivkov <walrus@amur.ru>
 * Copyright 2006      Deniz Adrian <adrian@netzquadrat.de>
 * Copyright 2013      Mats Erik Andersson <gnu@gisladisker.se>
 * Copyright 2017      Robert Krause <ruport@f00l.de>
 * Copyright 2017      Sharad B
 * Copyright 2020      David Polverari <david.polverari@gmail.com>
 * Copyright 2020      Jeroen Roovers <jer@gentoo.org>
 *
 * SPDX-License-Identifier: GPL-2.0-or-later
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA  02110-1301, USA.
 *
 * packit official page at https://github.com/resurrecting-open-source-projects/packit
 */
```
I think right now this will be the only change needed on each file. Later, should we have any file licensed with a different license, we could create a `LICENSES/` directory on the project root, move the current GPL license file to that directory with the name `GPL-2.0-or-later` and add the other licenses there as well, as per https://reuse.software/faq/.

So, if you're ok with that, I'm going to change the headers to look like the one shown in this comment.

**Comment by eribertomota** [comment]
Ok, I agree. Thanks!

**Comment by davidpolverari** [comment]
Already implemented. Closing.
