### ISSUE TITLE
Feature Request: latest version for ubuntu 18.04

### ISSUE THREAD

**Issue by xian18** [resurrecting-open-source-projects/packit#23]
I'm using Ubuntu 18.04 and the latest version is not installed with apt.
Restricted to the network environment, I can only install software from the apt's official source (lanuchpad) or its mirror.
I want to get new features like 802.11q , what do I need to do, or what additional adaptions do I need to do?

**Comment by jer-gentoo** [comment]
According to https://bugs.launchpad.net/ubuntu/+source/packit/+bugs newer Ubuntu releases support the latest packit version, so consider upgrading Ubuntu or compiling packit from source. Packit developers cannot help you do that.
